export const PREVIOUS_PHOTO = 'PREVIOUS_PHOTO'
export const NEXT_PHOTO = 'NEXT_PHOTO'

export const SET_SOURCE_PATH = 'SET_SOURCE_PATH'
export const SET_FILES = 'SET_FILES'

export const MARK_TO_DELETE = 'MARK_TO_DELETE'

export const GLOBAL_SPINNER_START = 'GLOBAL_SPINNER_START'
export const GLOBAL_SPINNER_STOP = 'GLOBAL_SPINNER_STOP'

export const RESET_SELECTED_FILE_INDEX = 'RESET_SELECTED_FILE_INDEX'

export const MODAL_OPEN_FOLDER_OPEN = 'MODAL_OPEN_FOLDER_OPEN'
export const MODAL_OPEN_FOLDER_CLOSE = 'MODAL_OPEN_FOLDER_CLOSE'
