export const PREVIOUS_PHOTO = 'PREVIOUS_PHOTO'
export const NEXT_PHOTO = 'NEXT_PHOTO'

export const SET_SOURCE_PATH = 'SET_SOURCE_PATH'
export const SET_FILES = 'SET_FILES'

export const MARK_TO_DELETE = 'MARK_TO_DELETE'

export const GLOBAL_SPINNER_START = 'GLOBAL_SPINNER_START'
export const GLOBAL_SPINNER_STOP = 'GLOBAL_SPINNER_STOP'
